/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Role */
        patch: operations["set_role_api_v1_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Password */
        patch: operations["set_password_api_v1_users__user_id__password_patch"];
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_api_v1_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_api_v1_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_api_v1_employees__employee_id__get"];
        put?: never;
        post?: never;
        /** Deactivate Employee */
        delete: operations["deactivate_employee_api_v1_employees__employee_id__delete"];
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_api_v1_employees__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee Team */
        get: operations["employee_team_api_v1_employees__employee_id__team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Archive Project */
        delete: operations["archive_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_projects__project_id__members_get"];
        put?: never;
        /** Assign Member */
        post: operations["assign_member_api_v1_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unassign Member */
        delete: operations["unassign_member_api_v1_projects__project_id__members__employee_id__delete"];
        options?: never;
        head?: never;
        /** Update Member Role */
        patch: operations["update_member_role_api_v1_projects__project_id__members__employee_id__patch"];
        trace?: never;
    };
    "/api/v1/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attendance */
        get: operations["list_attendance_api_v1_attendance_get"];
        put?: never;
        /** Create Attendance */
        post: operations["create_attendance_api_v1_attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attendance/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attendance */
        get: operations["get_attendance_api_v1_attendance__record_id__get"];
        put?: never;
        post?: never;
        /** Delete Attendance */
        delete: operations["delete_attendance_api_v1_attendance__record_id__delete"];
        options?: never;
        head?: never;
        /** Update Attendance */
        patch: operations["update_attendance_api_v1_attendance__record_id__patch"];
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employee Attendance */
        get: operations["list_employee_attendance_api_v1_employees__employee_id__attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Work Reports */
        get: operations["list_work_reports_api_v1_work_reports_get"];
        put?: never;
        /** Create Work Report */
        post: operations["create_work_report_api_v1_work_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Report */
        get: operations["get_work_report_api_v1_work_reports__report_id__get"];
        put?: never;
        post?: never;
        /** Delete Work Report */
        delete: operations["delete_work_report_api_v1_work_reports__report_id__delete"];
        options?: never;
        head?: never;
        /** Update Work Report */
        patch: operations["update_work_report_api_v1_work_reports__report_id__patch"];
        trace?: never;
    };
    "/api/v1/work-reports/{report_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Work Report */
        post: operations["submit_work_report_api_v1_work_reports__report_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-reports/{report_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Work Report */
        post: operations["approve_work_report_api_v1_work_reports__report_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-reports/{report_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Work Report */
        post: operations["reject_work_report_api_v1_work_reports__report_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendanceCreate */
        AttendanceCreate: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Attendance Date
             * Format: date
             */
            attendance_date: string;
            status: components["schemas"]["AttendanceStatus"];
            /** Check In At */
            check_in_at?: string | null;
            /** Check Out At */
            check_out_at?: string | null;
        };
        /** AttendanceOut */
        AttendanceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Attendance Date
             * Format: date
             */
            attendance_date: string;
            /** Check In At */
            check_in_at?: string | null;
            /** Check Out At */
            check_out_at?: string | null;
            /** Total Minutes */
            total_minutes: number;
            /** Overtime Minutes */
            overtime_minutes: number;
            status: components["schemas"]["AttendanceStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AttendancePage */
        AttendancePage: {
            /** Items */
            items: components["schemas"]["AttendanceOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * AttendanceStatus
         * @enum {string}
         */
        AttendanceStatus: "present" | "absent" | "half_day" | "leave" | "holiday" | "weekend";
        /** AttendanceUpdate */
        AttendanceUpdate: {
            status?: components["schemas"]["AttendanceStatus"] | null;
            /** Check In At */
            check_in_at?: string | null;
            /** Check Out At */
            check_out_at?: string | null;
        };
        /**
         * DayStatus
         * @enum {string}
         */
        DayStatus: "on_duty" | "half_day" | "on_leave" | "wfh" | "permission" | "comp_off";
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Employee Code */
            employee_code: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** User Id */
            user_id?: string | null;
            /** Work Email */
            work_email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Department */
            department?: string | null;
            /** Designation */
            designation?: string | null;
            /** Manager Id */
            manager_id?: string | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            /** @default active */
            status: components["schemas"]["EmployeeStatus"];
        };
        /** EmployeeOut */
        EmployeeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id?: string | null;
            /** Employee Code */
            employee_code: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Full Name */
            full_name: string;
            /** Work Email */
            work_email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Department */
            department?: string | null;
            /** Designation */
            designation?: string | null;
            /** Manager Id */
            manager_id?: string | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            status: components["schemas"]["EmployeeStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmployeePage */
        EmployeePage: {
            /** Items */
            items: components["schemas"]["EmployeeOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * EmployeeStatus
         * @enum {string}
         */
        EmployeeStatus: "active" | "on_leave" | "exited";
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Work Email */
            work_email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Department */
            department?: string | null;
            /** Designation */
            designation?: string | null;
            /** Manager Id */
            manager_id?: string | null;
            /** Date Of Joining */
            date_of_joining?: string | null;
            status?: components["schemas"]["EmployeeStatus"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            user: components["schemas"]["UserOut"];
            /** Employee */
            employee?: null;
            /** Employee Id */
            employee_id?: string | null;
        };
        /** PasswordUpdate */
        PasswordUpdate: {
            /** New Password */
            new_password: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Job Code Id */
            job_code_id?: string | null;
            /** Client */
            client?: string | null;
            /** Description */
            description?: string | null;
            /** @default planning */
            status: components["schemas"]["ProjectStatus"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ProjectMemberCreate */
        ProjectMemberCreate: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** @default contributor */
            role: components["schemas"]["ProjectMemberRole"];
        };
        /** ProjectMemberOut */
        ProjectMemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Employee Name */
            employee_name: string;
            role: components["schemas"]["ProjectMemberRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectMemberRole
         * @enum {string}
         */
        ProjectMemberRole: "team_lead" | "contributor" | "qc";
        /** ProjectMemberRoleUpdate */
        ProjectMemberRoleUpdate: {
            role: components["schemas"]["ProjectMemberRole"];
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Job Code Id */
            job_code_id?: string | null;
            /** Job Code Code — J-code string e.g. "J-615-2" */
            job_code_code?: string | null;
            /** Job Code Name — full label e.g. "EPIC FOR DUKHAN..." */
            job_code_name?: string | null;
            /** Client */
            client?: string | null;
            /** Description */
            description?: string | null;
            status: components["schemas"]["ProjectStatus"];
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Member Count
             * @default 0
             */
            member_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectPage */
        ProjectPage: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "planning" | "active" | "on_hold" | "completed" | "archived";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Job Code Id */
            job_code_id?: string | null;
            /** Client */
            client?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** RoleUpdate */
        RoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserPage */
        UserPage: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "project_manager" | "employee";
        /** UserUpdate */
        UserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkLocation
         * @enum {string}
         */
        WorkLocation: "hyderabad" | "chennai" | "qatar";
        /** WorkReportCreate */
        WorkReportCreate: {
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            day_status?: components["schemas"]["DayStatus"] | null;
            location?: components["schemas"]["WorkLocation"] | null;
            /** Remarks */
            remarks?: string | null;
            /** Query Text */
            query_text?: string | null;
            /** Well Head No */
            well_head_no?: string | null;
            /** Pm Plant */
            pm_plant?: string | null;
            /** Task List Count */
            task_list_count?: number | null;
            /** Task List Op Count */
            task_list_op_count?: number | null;
            /** Maintenance Item Count */
            maintenance_item_count?: number | null;
            /** Maintenance Plan Count */
            maintenance_plan_count?: number | null;
            /** Summary */
            summary?: string | null;
            /** Tasks */
            tasks: components["schemas"]["WorkReportTaskIn"][];
        };
        /** WorkReportOut */
        WorkReportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            status: components["schemas"]["WorkReportStatus"];
            day_status?: components["schemas"]["DayStatus"] | null;
            location?: components["schemas"]["WorkLocation"] | null;
            /** Remarks */
            remarks?: string | null;
            /** Query Text */
            query_text?: string | null;
            /** Well Head No */
            well_head_no?: string | null;
            /** Pm Plant */
            pm_plant?: string | null;
            /** Task List Count */
            task_list_count?: number | null;
            /** Task List Op Count */
            task_list_op_count?: number | null;
            /** Maintenance Item Count */
            maintenance_item_count?: number | null;
            /** Maintenance Plan Count */
            maintenance_plan_count?: number | null;
            /** Summary */
            summary?: string | null;
            /** Total Minutes */
            total_minutes: number;
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["WorkReportTaskOut"][];
            /** Submitted At */
            submitted_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Review Note */
            review_note?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WorkReportPage */
        WorkReportPage: {
            /** Items */
            items: components["schemas"]["WorkReportOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** WorkReportReject */
        WorkReportReject: {
            /** Review Note */
            review_note: string;
        };
        /**
         * WorkReportStatus
         * @enum {string}
         */
        WorkReportStatus: "draft" | "submitted" | "approved" | "rejected";
        /** WorkReportTaskIn */
        WorkReportTaskIn: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Description */
            description: string;
            /** Minutes Spent */
            minutes_spent?: number | null;
            /** Activity Type */
            activity_type?: string | null;
            /**
             * Tags Count
             * @default 0
             */
            tags_count: number;
            /**
             * Docs Count
             * @default 0
             */
            docs_count: number;
            /**
             * Bom Count
             * @default 0
             */
            bom_count: number;
            /**
             * Spares Count
             * @default 0
             */
            spares_count: number;
        };
        /** WorkReportTaskOut */
        WorkReportTaskOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Description */
            description: string;
            /** Minutes Spent */
            minutes_spent?: number | null;
            /** Activity Type */
            activity_type?: string | null;
            /**
             * Tags Count
             * @default 0
             */
            tags_count: number;
            /**
             * Docs Count
             * @default 0
             */
            docs_count: number;
            /**
             * Bom Count
             * @default 0
             */
            bom_count: number;
            /**
             * Spares Count
             * @default 0
             */
            spares_count: number;
        };
        /** WorkReportUpdate */
        WorkReportUpdate: {
            day_status?: components["schemas"]["DayStatus"] | null;
            location?: components["schemas"]["WorkLocation"] | null;
            /** Remarks */
            remarks?: string | null;
            /** Query Text */
            query_text?: string | null;
            /** Well Head No */
            well_head_no?: string | null;
            /** Pm Plant */
            pm_plant?: string | null;
            /** Task List Count */
            task_list_count?: number | null;
            /** Task List Op Count */
            task_list_op_count?: number | null;
            /** Maintenance Item Count */
            maintenance_item_count?: number | null;
            /** Maintenance Plan Count */
            maintenance_plan_count?: number | null;
            /** Summary */
            summary?: string | null;
            /** Tasks */
            tasks?: components["schemas"]["WorkReportTaskIn"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_v1_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v1_users__user_id__password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_api_v1_employees_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: components["schemas"]["EmployeeStatus"] | null;
                department?: string | null;
                manager_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_api_v1_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_api_v1_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_employee_api_v1_employees__employee_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_api_v1_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    employee_team_api_v1_employees__employee_id__team_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: components["schemas"]["ProjectStatus"] | null;
                employee_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_projects__project_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_member_api_v1_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unassign_member_api_v1_projects__project_id__members__employee_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_api_v1_projects__project_id__members__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attendance_api_v1_attendance_get: {
        parameters: {
            query?: {
                employee_id?: string | null;
                status?: components["schemas"]["AttendanceStatus"] | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendancePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attendance_api_v1_attendance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attendance_api_v1_attendance__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attendance_api_v1_attendance__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_attendance_api_v1_attendance__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employee_attendance_api_v1_employees__employee_id__attendance_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AttendanceStatus"] | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendancePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_reports_api_v1_work_reports_get: {
        parameters: {
            query?: {
                employee_id?: string | null;
                project_id?: string | null;
                status?: components["schemas"]["WorkReportStatus"] | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_work_report_api_v1_work_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_report_api_v1_work_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_work_report_api_v1_work_reports__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_work_report_api_v1_work_reports__report_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkReportUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_work_report_api_v1_work_reports__report_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_work_report_api_v1_work_reports__report_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_work_report_api_v1_work_reports__report_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkReportReject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
