"""Application settings, loaded from environment (.env).

Every setting is read from the environment / a `.env` file via pydantic-settings.
The literal values below are **local-development defaults only**; each is
overridden by the matching environment variable (or a line in `.env`) with no
source change. Precedence (highest first): process env vars (e.g. systemd
EnvironmentFile, docker-compose `environment:`) > `.env` file > these defaults.

Therefore production is configured entirely through `.env` on the server —
DO NOT edit this file to point at production Redis/DB/SMTP. See
backend/deploy/DEPLOYMENT.md and backend/.env.example.

`PRODUCT_NAME` is the single brand identifier (Naming Decision Record, D-001);
nothing else names the product.
"""
from functools import lru_cache

from pydantic import field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

_INSECURE_SECRET_DEFAULT = "change-me-in-production"
_MIN_SECRET_LENGTH = 32
# Only these environments may run with the insecure dev default secret.
_DEV_ENVS = frozenset({"local", "test"})
_ALLOWED_ENVS = frozenset({"local", "test", "staging", "production"})


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Runtime
    # Fail-closed default: an unset or mistyped ENV is treated as production,
    # so the SECRET_KEY guard below applies unless ENV is explicitly local/test.
    ENV: str = "production"
    API_V1_PREFIX: str = "/api/v1"
    PRODUCT_NAME: str = "CoreOps"

    # Security (consumed from V1 — Authentication)
    SECRET_KEY: str = "change-me-in-production"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60

    # Datastores.
    # Defaults target a HOST-run backend reaching the docker-published ports
    # (Postgres 5433, Redis 6381 — 6381 avoids colliding with SPIR's 6379 on the
    # shared dev box). Docker compose overrides these to db:5432 / redis:6379,
    # and production overrides them via .env (e.g. Redis on redis://localhost:6379).
    DATABASE_URL: str = "postgresql+psycopg://wms:wms@localhost:5433/wms"
    REDIS_URL: str = "redis://localhost:6381/0"
    CELERY_BROKER_URL: str = "redis://localhost:6381/1"

    # HTTP
    BACKEND_PORT: int = 8100
    CORS_ORIGINS: str = "http://localhost:3100"

    # Public base URL of the CoreOps web app, used to turn the relative paths
    # notifications already carry (e.g. /attendance/leave/<id>?from=...) into
    # absolute links for OUTBOUND EMAIL. Browser-facing pages never need it.
    #
    # Deliberately its own setting rather than something derived from
    # CORS_ORIGINS: that is a security allow-list which may hold several origins
    # in any order, and quietly borrowing its first entry would make an email
    # link depend on the order of a list nobody edits with links in mind.
    #
    # Empty (the default) means "no public URL configured", and every email
    # template omits its link rather than rendering a broken relative one. So
    # local dev and the test suite need no value at all.
    APP_BASE_URL: str = ""

    # Temporary notification debug endpoints (/debug/*). Off by default; enable
    # only for verifying the email/reminder pipeline. Guarded by PM role too.
    ENABLE_DEBUG_ENDPOINTS: bool = False

    # Interactive API docs (Swagger UI, ReDoc and the openapi.json schema).
    # Fail-closed default: production publishes no schema surface unless this is
    # explicitly turned on. When false, app.main passes None for all three URLs,
    # so the routes are never mounted and requests to them 404. Turning it on
    # does NOT change any router prefix or endpoint URL.
    ENABLE_API_DOCS: bool = False

    # Task continuation (work_items). ON by default since Phase 2 (lump-sum
    # continuation approval) builds directly on this engine. When true, saving
    # a TASK_BASED/TASK_STATUS_ONLY/TASK_WITH_QUANTITY row creates/links a
    # WorkItem so one activity can span several daily reports with a fixed
    # (working-day) deadline. The frontend reads the mirror flag
    # NEXT_PUBLIC_FEATURE_TASK_CONTINUATION; keep the two in step per
    # environment.
    TASK_CONTINUATION_ENABLED: bool = True

    # Split-day work reports (work_report_periods, migration 0060). Off by
    # default. Periods are ALWAYS maintained internally (every report gets a
    # Full-Day period; legacy payloads are translated) — this flag only gates
    # whether report_mode='split_day' payloads are accepted, so old full-day
    # behaviour is byte-identical while disabled. The frontend reads the mirror
    # flag NEXT_PUBLIC_REPORT_DAY_PARTS_ENABLED; keep the two in step per
    # environment.
    REPORT_DAY_PARTS_ENABLED: bool = False

    # --- EasyTime biometric ingestion (Phase 2, migration 0066) -------------
    # Master switch for the office-connector ingestion endpoint
    # (POST {prefix}/integrations/easytime/punches/batch). Off by default: while
    # false the route is mounted but answers 404 to everyone, so no biometric
    # data can enter the system. Turning it on changes NOTHING about existing
    # attendance, leave, reports or exports — punches land in their own tables.
    EASYTIME_INGESTION_ENABLED: bool = False

    # Shared secret the office-side connector presents in the
    # X-CoreOps-Connector-Token header. NOT a user JWT and never a query
    # parameter. Compared with secrets.compare_digest. Set it only in the
    # server .env; it must never be logged, echoed or committed.
    EASYTIME_CONNECTOR_TOKEN: str = ""

    # Timezone used to interpret a NAIVE biometric timestamp. EasyTime returns
    # naive local wall-clock values; the connector normally attaches the offset,
    # and this is the fallback when it does not.
    ATTENDANCE_TIMEZONE: str = "Asia/Kolkata"

    # Whether an EasyTime employee code with no explicit mapping row may fall
    # back to an EXACT, case-sensitive match on employees.employee_code. That
    # column carries a partial unique index, so the match is deterministic (at
    # most one row) and can never silently pick the wrong employee. Explicit
    # mappings always win. Names are never used for matching.
    BIOMETRIC_EXACT_CODE_MATCH_ENABLED: bool = True

    @property
    def cors_origins_list(self) -> list[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",") if o.strip()]

    @field_validator("ENV")
    @classmethod
    def _validate_env(cls, value: str) -> str:
        if value not in _ALLOWED_ENVS:
            raise ValueError(
                f"ENV must be one of {sorted(_ALLOWED_ENVS)}; got {value!r}."
            )
        return value

    @model_validator(mode="after")
    def _guard_secret_key(self) -> "Settings":
        # Fail closed: only dev/test envs may use the insecure default secret.
        if self.ENV not in _DEV_ENVS:
            if (
                self.SECRET_KEY == _INSECURE_SECRET_DEFAULT
                or len(self.SECRET_KEY) < _MIN_SECRET_LENGTH
            ):
                raise ValueError(
                    f"SECRET_KEY must be a strong, non-default value "
                    f"(>= {_MIN_SECRET_LENGTH} chars) when ENV is {self.ENV!r}."
                )
        return self

    @model_validator(mode="after")
    def _guard_connector_token(self) -> "Settings":
        # Fail closed: outside dev/test, biometric ingestion may not be enabled
        # without a strong connector token. Refusing to boot is safer than
        # serving an ingestion endpoint guarded by an empty or guessable secret.
        if self.EASYTIME_INGESTION_ENABLED and self.ENV not in _DEV_ENVS:
            token = self.EASYTIME_CONNECTOR_TOKEN or ""
            if len(token) < _MIN_SECRET_LENGTH:
                raise ValueError(
                    f"EASYTIME_CONNECTOR_TOKEN must be a strong, non-empty value "
                    f"(>= {_MIN_SECRET_LENGTH} chars) when "
                    f"EASYTIME_INGESTION_ENABLED is true and ENV is {self.ENV!r}."
                )
        return self


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
